### PR TITLE
bugfix/PP-14296: Plugin Shopware 6: New Cancelation Endpoint not respecting Error / Failed Redirect Url (Shopware 6)

### LINKED ISSUE #40: New Cancelation Endpoint not respecting Error / Failed Redirect Url
When using the new Plugin Version with the new cancel endpoint "Failed URL" which is defined in our Headless Frontend is not recognized any more. The "hardcoded" redirect is making problems. This is because with the new endpoint the finalize method of the paymnetHandler is not used any more, which take automaticly care of the correct redirect which is handed over to it.

Can you please add the possibility to "use automatic redirects via the finanlize method" as a config option for headless shops, or implement it in the correct workflow way of shopware. 

For now the workaround is for us:

` /*$cancelUrl = $this->router->generate('frontend.payrexx-payment.cancel',
            [
                'orderId' => $order->getOrderNumber(),
                'transactionId' => $transactionId,
            ],
            UrlGeneratorInterface::ABSOLUTE_URL
        );*/
        $cancelUrl = $transaction->getReturnUrl();`

### PR DESCRIPTION
**Pull request by vinothss4u**
Fixed redirect cancel url for store api.

Closes #40

### CODE REVIEW

File: PayrexxPaymentGatewaySW6/src/Handler/PaymentHandler.php [hunk 1]
```diff
@@ -186,13 +195,25 @@ public function pay(AsyncPaymentTransactionStruct $transaction, RequestDataBag $
...
             throw new Exception('Unavailable payment method error');
         }
-        $cancelUrl = $this->router->generate('frontend.payrexx-payment.cancel',
-            [
-                'orderId' => $order->getOrderNumber(),
-                'transactionId' => $transactionId,
-            ],
-            UrlGeneratorInterface::ABSOLUTE_URL
-        );
+
```
Comment (mathis-hermann) [inline PayrexxPaymentGatewaySW6/src/Handler/PaymentHandler.php:198]: extract this logic into a new function.
could return an array with the needed urls
```
private function createReturnUrl(...) {
  ...
  return [
    'returnUrl' => ... ,
    'cancelUrl' => ... ,
  ];
}
```

**Review by mathis-hermann — CHANGES_REQUESTED** [review]

File: PayrexxPaymentGatewaySW6/src/Handler/PaymentHandler.php (hunk 1 above)
Comment (vinothss4u) [reply PayrexxPaymentGatewaySW6/src/Handler/PaymentHandler.php:198]: @mathis-hermann 

Done. Please check

File: PayrexxPaymentGatewaySW6/src/Handler/PaymentHandler.php [hunk 2]
```diff
@@ -436,4 +443,39 @@ public function customCustomerException($transactionId, $message)
...
+        AsyncPaymentTransactionStruct $transaction,
+        string $orderNumber,
+        string $transactionId
+    ): array {
+        $returnUrl = $transaction->getReturnUrl();
+        $request = $this->requestStack->getCurrentRequest();
+        $urlPath = $request ? $request->getPathInfo() : '';
+
+        // Check if the request comes from Store API (headless frontend)
+        $isStoreApiRequest = str_starts_with($urlPath, '/store-api');
```
Comment (mathis-hermann) [inline PayrexxPaymentGatewaySW6/src/Handler/PaymentHandler.php:465]: `str_starts_with()` is only available with PHP 8. Please make it PHP 7.4 compatible.

**Review by mathis-hermann — CHANGES_REQUESTED** [review]

File: PayrexxPaymentGatewaySW6/src/Handler/PaymentHandler.php (hunk 2 above)
Comment (vinothss4u) [reply PayrexxPaymentGatewaySW6/src/Handler/PaymentHandler.php]: @mathis-hermann 

Done.

**Review by mathis-hermann — APPROVED** [review]
Thanks for the fix.
